server.port=8080

spring.config.import=optional:file:secrets.env[.properties]
spring.ai.mcp.client.streamable-http.connections.helpdesk.url=http://localhost:8081
spring.profiles.active=google

spring.threads.virtual.enabled=true
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.request-timeout=120s

